#!/bin/bash
# Generate Repository Inventory
# Output: docs/constitution/REPO_INVENTORY.md

set -euo pipefail

OUTPUT_FILE="docs/constitution/REPO_INVENTORY.md"

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo "Generating repository inventory..."

cat > "$OUTPUT_FILE" << 'EOF'
# Repository Inventory

This document is auto-generated by `scripts/generate_inventory.sh`.

## Top-Level Directories

EOF

# Count top-level directories and files
echo "## Top-Level Directories" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
for dir in */; do
    if [ -d "$dir" ]; then
        dir_name="${dir%/}"
        file_count=$(find "$dir" -type f 2>/dev/null | grep -v ".venv" | wc -l | tr -d ' ')
        echo "- \`$dir_name/\`: $file_count files" >> "$OUTPUT_FILE"
    fi
done

echo "" >> "$OUTPUT_FILE"
echo "## Empty Directories (containing only .gitkeep)" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Find empty directories or directories with only .gitkeep
empty_dirs=()
for dir in */; do
    if [ -d "$dir" ]; then
        dir_name="${dir%/}"
        # Skip .venv and other build artifacts
        if [[ "$dir_name" == ".venv" ]] || [[ "$dir_name" == "build" ]] || [[ "$dir_name" == "DerivedData" ]]; then
            continue
        fi
        
        files=$(find "$dir" -type f 2>/dev/null | grep -v ".venv" | grep -v ".git" || true)
        if [ -z "$files" ] || [ "$(echo "$files" | wc -l | tr -d ' ')" -eq 0 ]; then
            empty_dirs+=("$dir_name")
            echo "- \`$dir_name/\`" >> "$OUTPUT_FILE"
        elif [ "$(echo "$files" | wc -l | tr -d ' ')" -eq 1 ] && echo "$files" | grep -q "\.gitkeep$"; then
            empty_dirs+=("$dir_name")
            echo "- \`$dir_name/\` (contains only .gitkeep)" >> "$OUTPUT_FILE"
        fi
    fi
done

if [ ${#empty_dirs[@]} -eq 0 ]; then
    echo "No empty directories found." >> "$OUTPUT_FILE"
fi

echo "" >> "$OUTPUT_FILE"
echo "## Risk Assessment" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "### Directories That May Still Be in Xcode Target Membership" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "⚠️ **Manual Check Required**: The following directories may still be referenced in Xcode project targets:" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "- \`Core/Camera/\` - Check Build Phases → Compile Sources" >> "$OUTPUT_FILE"
echo "- \`Core/PointCloud/\` - Check Build Phases → Compile Sources" >> "$OUTPUT_FILE"
echo "- \`Core/Training/\` - Check Build Phases → Compile Sources (may contain Shaders/)" >> "$OUTPUT_FILE"
echo "- \`Features/\` - Check Build Phases → Compile Sources (may contain subdirectories)" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

echo "### Pre-Deletion Verification Actions" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "Before deleting any directory, verify:" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "1. **Core/Training/**: Check for shader files:" >> "$OUTPUT_FILE"
echo "   \`\`\`bash" >> "$OUTPUT_FILE"
echo "   find Core/Training -type f -name '*.metal' -o -name '*.glsl' -o -name '*.shader'" >> "$OUTPUT_FILE"
echo "   \`\`\`" >> "$OUTPUT_FILE"
echo "   - If shader files exist: DO NOT DELETE. Move Shaders/ to appropriate location first." >> "$OUTPUT_FILE"
echo "   - If empty or only .gitkeep: Safe to delete." >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "2. **Features/**: Check Xcode Compile Sources:" >> "$OUTPUT_FILE"
echo "   - Open Xcode project" >> "$OUTPUT_FILE"
echo "   - Navigate to Build Phases → Compile Sources" >> "$OUTPUT_FILE"
echo "   - Search for 'Features/' in the list" >> "$OUTPUT_FILE"
echo "   - If found: DO NOT DELETE. Remove from target first." >> "$OUTPUT_FILE"
echo "   - If not found: Safe to delete." >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "3. **Core/Camera/ and Core/PointCloud/**: Check if empty:" >> "$OUTPUT_FILE"
echo "   \`\`\`bash" >> "$OUTPUT_FILE"
echo "   find Core/Camera Core/PointCloud -type f 2>/dev/null | grep -v '.gitkeep'" >> "$OUTPUT_FILE"
echo "   \`\`\`" >> "$OUTPUT_FILE"
echo "   - If output is empty: Safe to delete." >> "$OUTPUT_FILE"
echo "   - If files found: DO NOT DELETE." >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

echo -e "${GREEN}✅ Repository inventory generated: $OUTPUT_FILE${NC}"

