inherit_from: "configs/mono/tum/fr3_office.yaml"

Results:
  save_dir: "/root/donor_whitebox/outputs/monogs_runs"
  use_gui: False
  eval_rendering: False

Dataset:
  dataset_path: "/root/donor_whitebox/outputs/monogs_room3x3_tumlike_monogs_tum32p1_fr3_exact_20260310"
  single_thread: True

Training:
  single_thread: True
  kf_interval: 1
