inherit_from: "/root/donor_whitebox/configs/wildgs_official_tum_freiburg3_sitting_static_clean.yaml"

single_thread: True

scene: room3x3_tumrgbd_wildgs_static_20260314_p2d

data:
  input_folder: "/root/donor_whitebox/outputs/wildgs_room3x3_tumrgbd_wildgs_static_20260314_p2d"
  output: "/root/donor_whitebox/outputs/wildgs_runs/room3x3_tumrgbd_wildgs_static_20260314_p2d"
