#!/usr/bin/env bash
set -euo pipefail

CONTROL_PLANE_ROOT="${CONTROL_PLANE_ROOT:-/root/control_plane}"
CONTROL_PLANE_BIND_HOST="${CONTROL_PLANE_BIND_HOST:-0.0.0.0}"
CONTROL_PLANE_PORT="${CONTROL_PLANE_PORT:-8787}"
CONTROL_PLANE_PUBLIC_BASE_URL="${CONTROL_PLANE_PUBLIC_BASE_URL:?CONTROL_PLANE_PUBLIC_BASE_URL is required}"
CONTROL_PLANE_ENVIRONMENT="${CONTROL_PLANE_ENVIRONMENT:-production}"
CONTROL_PLANE_API_INGRESS_MODE="${CONTROL_PLANE_API_INGRESS_MODE:-direct_tls}"
CONTROL_PLANE_STORAGE_MODE="${CONTROL_PLANE_STORAGE_MODE:-managed}"
CONTROL_PLANE_OBJECT_STORAGE_PROVIDER="${CONTROL_PLANE_OBJECT_STORAGE_PROVIDER:-s3_compatible}"
CONTROL_PLANE_OBJECT_STORAGE_ENDPOINT_URL="${CONTROL_PLANE_OBJECT_STORAGE_ENDPOINT_URL:-}"
CONTROL_PLANE_OBJECT_STORAGE_REGION="${CONTROL_PLANE_OBJECT_STORAGE_REGION:-}"
CONTROL_PLANE_OBJECT_STORAGE_BUCKET="${CONTROL_PLANE_OBJECT_STORAGE_BUCKET:-aether-control}"
CONTROL_PLANE_OBJECT_STORAGE_ACCESS_KEY_ID="${CONTROL_PLANE_OBJECT_STORAGE_ACCESS_KEY_ID:-}"
CONTROL_PLANE_OBJECT_STORAGE_SECRET_ACCESS_KEY="${CONTROL_PLANE_OBJECT_STORAGE_SECRET_ACCESS_KEY:-}"
CONTROL_PLANE_OBJECT_STORAGE_SESSION_TOKEN="${CONTROL_PLANE_OBJECT_STORAGE_SESSION_TOKEN:-}"
CONTROL_PLANE_OBJECT_STORAGE_PUBLIC_BASE_URL="${CONTROL_PLANE_OBJECT_STORAGE_PUBLIC_BASE_URL:-}"
CONTROL_PLANE_OBJECT_STORAGE_ADDRESSING_STYLE="${CONTROL_PLANE_OBJECT_STORAGE_ADDRESSING_STYLE:-auto}"
CONTROL_PLANE_OBJECT_STORAGE_PRESIGN_EXPIRY_SEC="${CONTROL_PLANE_OBJECT_STORAGE_PRESIGN_EXPIRY_SEC:-3600}"
CONTROL_PLANE_OBJECT_STORAGE_MULTIPART_THRESHOLD_BYTES="${CONTROL_PLANE_OBJECT_STORAGE_MULTIPART_THRESHOLD_BYTES:-5242880}"
CONTROL_PLANE_OBJECT_STORAGE_MULTIPART_PART_SIZE_BYTES="${CONTROL_PLANE_OBJECT_STORAGE_MULTIPART_PART_SIZE_BYTES:-16777216}"
CONTROL_PLANE_OBJECT_STORAGE_MULTIPART_MAX_CONCURRENCY="${CONTROL_PLANE_OBJECT_STORAGE_MULTIPART_MAX_CONCURRENCY:-20}"
CONTROL_PLANE_OBJECT_STORAGE_CHUNKED_INGEST_ENABLED="${CONTROL_PLANE_OBJECT_STORAGE_CHUNKED_INGEST_ENABLED:-true}"
CONTROL_PLANE_OBJECT_STORAGE_CHUNKED_INGEST_THRESHOLD_BYTES="${CONTROL_PLANE_OBJECT_STORAGE_CHUNKED_INGEST_THRESHOLD_BYTES:-5242880}"
CONTROL_PLANE_OBJECT_STORAGE_CHUNKED_INGEST_CHUNK_SIZE_BYTES="${CONTROL_PLANE_OBJECT_STORAGE_CHUNKED_INGEST_CHUNK_SIZE_BYTES:-8388608}"
CONTROL_PLANE_OBJECT_STORAGE_CHUNKED_INGEST_MAX_CONCURRENCY="${CONTROL_PLANE_OBJECT_STORAGE_CHUNKED_INGEST_MAX_CONCURRENCY:-20}"
CONTROL_PLANE_OBJECT_STORAGE_CHUNKED_INGEST_MIN_READY_BYTES="${CONTROL_PLANE_OBJECT_STORAGE_CHUNKED_INGEST_MIN_READY_BYTES:-33554432}"
MINIO_API_PORT="${MINIO_API_PORT:-9000}"
MINIO_CONSOLE_PORT="${MINIO_CONSOLE_PORT:-9001}"
POSTGRES_DB="${POSTGRES_DB:-aether_control}"
POSTGRES_USER="${POSTGRES_USER:-aether}"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-aetherpass}"
MINIO_ROOT_USER="${MINIO_ROOT_USER:-aetherminio}"
MINIO_ROOT_PASSWORD="${MINIO_ROOT_PASSWORD:-aetherminiosecret}"

export DEBIAN_FRONTEND=noninteractive

ensure_apt_packages() {
  local missing=()
  local pkg
  for pkg in "$@"; do
    if ! dpkg -s "${pkg}" >/dev/null 2>&1; then
      missing+=("${pkg}")
    fi
  done

  if (( ${#missing[@]} == 0 )); then
    return
  fi

  apt-get update
  apt-get install -y "${missing[@]}"
}

infer_object_storage_region() {
  local raw="${1:-}"
  raw="${raw#http://}"
  raw="${raw#https://}"
  raw="${raw%%/*}"

  if [[ -z "${raw}" ]]; then
    printf 'auto\n'
    return
  fi

  if [[ "${raw}" == *.digitaloceanspaces.com ]]; then
    local first="${raw%%.*}"
    local rest="${raw#*.}"
    if [[ "${rest}" == "digitaloceanspaces.com" ]]; then
      printf '%s\n' "${first}"
      return
    fi
    printf '%s\n' "${rest%%.*}"
    return
  fi

  printf 'auto\n'
}

if [[ -z "${CONTROL_PLANE_OBJECT_STORAGE_REGION}" || "${CONTROL_PLANE_OBJECT_STORAGE_REGION}" == "auto" ]]; then
  CONTROL_PLANE_OBJECT_STORAGE_REGION="$(infer_object_storage_region "${CONTROL_PLANE_OBJECT_STORAGE_ENDPOINT_URL}")"
fi

ensure_apt_packages ca-certificates curl python3-venv postgresql postgresql-client

systemctl enable postgresql >/dev/null 2>&1 || true
systemctl start postgresql >/dev/null 2>&1 || true

if command -v pg_lsclusters >/dev/null 2>&1; then
  POSTGRES_CLUSTER_VERSION="$(pg_lsclusters --no-header | awk 'NR==1 {print $1}')"
  POSTGRES_CLUSTER_NAME="$(pg_lsclusters --no-header | awk 'NR==1 {print $2}')"
  if [[ -n "${POSTGRES_CLUSTER_VERSION:-}" && -n "${POSTGRES_CLUSTER_NAME:-}" ]]; then
    pg_ctlcluster "${POSTGRES_CLUSTER_VERSION}" "${POSTGRES_CLUSTER_NAME}" start >/dev/null 2>&1 || true
  fi
fi

cd "${CONTROL_PLANE_ROOT}"

find "${CONTROL_PLANE_ROOT}" -name '._*' -delete

runuser -u postgres -- psql -v ON_ERROR_STOP=1 <<SQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${POSTGRES_USER}') THEN
    CREATE ROLE ${POSTGRES_USER} WITH LOGIN PASSWORD '${POSTGRES_PASSWORD}';
  END IF;
END
\$\$;
SQL

if ! runuser -u postgres -- psql -Atqc "SELECT 1 FROM pg_database WHERE datname = '${POSTGRES_DB}'" | grep -q 1; then
  runuser -u postgres -- psql -v ON_ERROR_STOP=1 -c "CREATE DATABASE ${POSTGRES_DB} OWNER ${POSTGRES_USER};"
fi

runuser -u postgres -- psql -v ON_ERROR_STOP=1 -d "${POSTGRES_DB}" <<SQL
ALTER DATABASE ${POSTGRES_DB} OWNER TO ${POSTGRES_USER};
ALTER SCHEMA public OWNER TO ${POSTGRES_USER};
GRANT ALL ON SCHEMA public TO ${POSTGRES_USER};
SQL

python3 -m venv .venv
. .venv/bin/activate
pip install --upgrade pip
pip install -r requirements.txt

PGPASSWORD="${POSTGRES_PASSWORD}" psql -h 127.0.0.1 -U "${POSTGRES_USER}" -v ON_ERROR_STOP=1 "${POSTGRES_DB}" \
  < "${CONTROL_PLANE_ROOT}/migrations/0001_initial.sql"

mkdir -p /root/control-plane-logs

if [[ "${CONTROL_PLANE_STORAGE_MODE}" == "local_minio" ]]; then
  if ! command -v minio >/dev/null 2>&1; then
    curl -fsSL https://dl.min.io/server/minio/release/linux-amd64/minio -o /usr/local/bin/minio
    chmod +x /usr/local/bin/minio
  fi

  mkdir -p /root/minio-data /root/minio-config

  if [[ -z "${CONTROL_PLANE_OBJECT_STORAGE_PUBLIC_BASE_URL}" ]]; then
    CONTROL_PLANE_OBJECT_STORAGE_PUBLIC_BASE_URL="${CONTROL_PLANE_PUBLIC_BASE_URL%/}/${CONTROL_PLANE_OBJECT_STORAGE_BUCKET}"
  fi

  if [[ -z "${CONTROL_PLANE_OBJECT_STORAGE_ENDPOINT_URL}" ]]; then
    CONTROL_PLANE_OBJECT_STORAGE_ENDPOINT_URL="http://127.0.0.1:${MINIO_API_PORT}"
  fi

  if [[ -z "${CONTROL_PLANE_OBJECT_STORAGE_ACCESS_KEY_ID}" ]]; then
    CONTROL_PLANE_OBJECT_STORAGE_ACCESS_KEY_ID="${MINIO_ROOT_USER}"
  fi

  if [[ -z "${CONTROL_PLANE_OBJECT_STORAGE_SECRET_ACCESS_KEY}" ]]; then
    CONTROL_PLANE_OBJECT_STORAGE_SECRET_ACCESS_KEY="${MINIO_ROOT_PASSWORD}"
  fi

  nohup env MINIO_ROOT_USER="${MINIO_ROOT_USER}" MINIO_ROOT_PASSWORD="${MINIO_ROOT_PASSWORD}" \
    /usr/local/bin/minio server /root/minio-data --address ":${MINIO_API_PORT}" --console-address ":${MINIO_CONSOLE_PORT}" \
    >/root/control-plane-logs/minio.log 2>&1 &

  sleep 2

  python3 - <<PY
import boto3
from botocore.config import Config

endpoint = "${CONTROL_PLANE_OBJECT_STORAGE_ENDPOINT_URL}"
bucket = "${CONTROL_PLANE_OBJECT_STORAGE_BUCKET}"
client = boto3.client(
    "s3",
    endpoint_url=endpoint,
    aws_access_key_id="${CONTROL_PLANE_OBJECT_STORAGE_ACCESS_KEY_ID}",
    aws_secret_access_key="${CONTROL_PLANE_OBJECT_STORAGE_SECRET_ACCESS_KEY}",
    region_name="${CONTROL_PLANE_OBJECT_STORAGE_REGION}",
    config=Config(signature_version="s3v4", s3={"addressing_style": "${CONTROL_PLANE_OBJECT_STORAGE_ADDRESSING_STYLE}"}),
)
existing = {item["Name"] for item in client.list_buckets().get("Buckets", [])}
if bucket not in existing:
    client.create_bucket(Bucket=bucket)
print("BUCKET_OK")
PY
else
  : "${CONTROL_PLANE_OBJECT_STORAGE_ENDPOINT_URL:?CONTROL_PLANE_OBJECT_STORAGE_ENDPOINT_URL is required for managed storage}"
  : "${CONTROL_PLANE_OBJECT_STORAGE_BUCKET:?CONTROL_PLANE_OBJECT_STORAGE_BUCKET is required for managed storage}"
  : "${CONTROL_PLANE_OBJECT_STORAGE_ACCESS_KEY_ID:?CONTROL_PLANE_OBJECT_STORAGE_ACCESS_KEY_ID is required for managed storage}"
  : "${CONTROL_PLANE_OBJECT_STORAGE_SECRET_ACCESS_KEY:?CONTROL_PLANE_OBJECT_STORAGE_SECRET_ACCESS_KEY is required for managed storage}"
  : "${CONTROL_PLANE_OBJECT_STORAGE_PUBLIC_BASE_URL:?CONTROL_PLANE_OBJECT_STORAGE_PUBLIC_BASE_URL is required for managed storage}"
fi

cat > "${CONTROL_PLANE_ROOT}/.env.runtime" <<ENV
CONTROL_PLANE_ENVIRONMENT=${CONTROL_PLANE_ENVIRONMENT}
CONTROL_PLANE_API_INGRESS_MODE=${CONTROL_PLANE_API_INGRESS_MODE}
CONTROL_PLANE_PUBLIC_BASE_URL=${CONTROL_PLANE_PUBLIC_BASE_URL}
CONTROL_PLANE_DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@127.0.0.1:5432/${POSTGRES_DB}
CONTROL_PLANE_OBJECT_STORAGE_PROVIDER=${CONTROL_PLANE_OBJECT_STORAGE_PROVIDER}
CONTROL_PLANE_OBJECT_STORAGE_ENDPOINT_URL=${CONTROL_PLANE_OBJECT_STORAGE_ENDPOINT_URL}
CONTROL_PLANE_OBJECT_STORAGE_REGION=${CONTROL_PLANE_OBJECT_STORAGE_REGION}
CONTROL_PLANE_OBJECT_STORAGE_BUCKET=${CONTROL_PLANE_OBJECT_STORAGE_BUCKET}
CONTROL_PLANE_OBJECT_STORAGE_ACCESS_KEY_ID=${CONTROL_PLANE_OBJECT_STORAGE_ACCESS_KEY_ID}
CONTROL_PLANE_OBJECT_STORAGE_SECRET_ACCESS_KEY=${CONTROL_PLANE_OBJECT_STORAGE_SECRET_ACCESS_KEY}
CONTROL_PLANE_OBJECT_STORAGE_SESSION_TOKEN=${CONTROL_PLANE_OBJECT_STORAGE_SESSION_TOKEN}
CONTROL_PLANE_OBJECT_STORAGE_PUBLIC_BASE_URL=${CONTROL_PLANE_OBJECT_STORAGE_PUBLIC_BASE_URL}
CONTROL_PLANE_OBJECT_STORAGE_ADDRESSING_STYLE=${CONTROL_PLANE_OBJECT_STORAGE_ADDRESSING_STYLE}
CONTROL_PLANE_OBJECT_STORAGE_PRESIGN_EXPIRY_SEC=${CONTROL_PLANE_OBJECT_STORAGE_PRESIGN_EXPIRY_SEC}
CONTROL_PLANE_OBJECT_STORAGE_MULTIPART_THRESHOLD_BYTES=${CONTROL_PLANE_OBJECT_STORAGE_MULTIPART_THRESHOLD_BYTES}
CONTROL_PLANE_OBJECT_STORAGE_MULTIPART_PART_SIZE_BYTES=${CONTROL_PLANE_OBJECT_STORAGE_MULTIPART_PART_SIZE_BYTES}
CONTROL_PLANE_OBJECT_STORAGE_MULTIPART_MAX_CONCURRENCY=${CONTROL_PLANE_OBJECT_STORAGE_MULTIPART_MAX_CONCURRENCY}
CONTROL_PLANE_OBJECT_STORAGE_CHUNKED_INGEST_ENABLED=${CONTROL_PLANE_OBJECT_STORAGE_CHUNKED_INGEST_ENABLED}
CONTROL_PLANE_OBJECT_STORAGE_CHUNKED_INGEST_THRESHOLD_BYTES=${CONTROL_PLANE_OBJECT_STORAGE_CHUNKED_INGEST_THRESHOLD_BYTES}
CONTROL_PLANE_OBJECT_STORAGE_CHUNKED_INGEST_CHUNK_SIZE_BYTES=${CONTROL_PLANE_OBJECT_STORAGE_CHUNKED_INGEST_CHUNK_SIZE_BYTES}
CONTROL_PLANE_OBJECT_STORAGE_CHUNKED_INGEST_MAX_CONCURRENCY=${CONTROL_PLANE_OBJECT_STORAGE_CHUNKED_INGEST_MAX_CONCURRENCY}
CONTROL_PLANE_OBJECT_STORAGE_CHUNKED_INGEST_MIN_READY_BYTES=${CONTROL_PLANE_OBJECT_STORAGE_CHUNKED_INGEST_MIN_READY_BYTES}
ENV

set -a
. "${CONTROL_PLANE_ROOT}/.env.runtime"
set +a

nohup .venv/bin/python -m uvicorn app.main:app --host "${CONTROL_PLANE_BIND_HOST}" --port "${CONTROL_PLANE_PORT}" \
  >/root/control-plane-logs/control-plane.log 2>&1 &

sleep 2
curl -fsS "http://127.0.0.1:${CONTROL_PLANE_PORT}/health"
echo
echo "CONTROL_PLANE_READY"
